name: Simple CI

# 🔹 Запускаем CI не только при push, но и при pull_request (для проверки PR)
on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Say Hello
        run: echo "Hello CI!"
        
      - name: Simple test
        run: |
          python -c "
          from math_operations import add_numbers
          
          # Тест 1
          result1 = add_numbers(2, 3)
          print(f'2 + 3 = {result1}')
          assert result1 == 5, 'Ошибка: 2+3 должно быть 5'
          
          # Тест 2
          result2 = add_numbers(10, 5)
          print(f'10 + 5 = {result2}')
          assert result2 == 15, 'Ошибка: 10+5 должно быть 15'
          
          print('✅ Все тесты новой функции пройдены!')
          "

      - name: Generate auto-docs
        if: github.ref == 'refs/heads/main'
        run: |
          echo "📋 Создаю автоматическую документацию..."
          
          # Создаем папку для docs если её нет
          mkdir -p docs
          
          # Генерируем простой README с информацией о проекте
          echo "# Автоматическая документация" > docs/AUTO_GENERATED.md
          echo "" >> docs/AUTO_GENERATED.md
          echo "**Дата генерации:** $(date)" >> docs/AUTO_GENERATED.md
          echo "**Коммит:** ${{ github.sha }}" >> docs/AUTO_GENERATED.md
          echo "**Ветка:** ${{ github.ref }}" >> docs/AUTO_GENERATED.md
          echo "" >> docs/AUTO_GENERATED.md
          echo "## 🧪 Результаты тестов" >> docs/AUTO_GENERATED.md
          echo "Все тесты пройдены успешно! ✅" >> docs/AUTO_GENERATED.md
          echo "" >> docs/AUTO_GENERATED.md
          echo "## 📁 Структура проекта" >> docs/AUTO_GENERATED.md
          echo '```' >> docs/AUTO_GENERATED.md
          ls -la >> docs/AUTO_GENERATED.md
          echo '```' >> docs/AUTO_GENERATED.md
          
          echo "✅ Документация создана: docs/AUTO_GENERATED.md"
          
      - name: Save docs as artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: auto-documentation
          path: docs/AUTO_GENERATED.md